{
    "name": "Quản lý Campaign Email - Vinatex Đà Nẵng",
    "version": "17.0.1.0.0",
    "summary": "Gửi email marketing, phân nhóm khách hàng và tạo campaign remarketing",
    "category": "Marketing",
    "depends": ["base", "mail", "utm"],
    "data": [
        "security/ir.model.access.csv",
        "data/email_template.xml",
        "data/cleanup_templates.xml",
        "data/cron_send_campaign.xml",
        "views/mail_campaign_views.xml",
        "views/mail_template_views.xml",
        "views/schedule_campaign_wizard_views.xml",
        "views/campaign_menu.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
