{
    "name": "Dịch vụ CRM Thục Linh",
    "summary": "Quản lý phản hồi khách hàng, khiếu nại và SLA",
    "version": "19.0.1.0.0",
    "category": "Sales/CRM",
    "author": "Thuc Linh",
    "license": "LGPL-3",
    "depends": ["crm", "mail", "portal"],
    "data": [
        "security/ir.model.access.csv",
        "security/feedback_complaint_rules.xml",
        "data/complaint_sequence.xml",
        "data/feedback_sequence.xml",
        "data/feedback_mail_template.xml",
        "views/feedback_views.xml",
        "views/complaint_ticket_views.xml",
        "views/portal_templates.xml",
        "views/crm_lead_views.xml",
        "views/crm_dashboard_views.xml",
        "views/menu_views.xml",
    ],
    "application": True,
    "installable": True,
}
