from . import lead_management
from . import lead_data_approval
from . import cskh_profile
from . import cskh_workflow_rule
from . import cskh_lead
from . import complaint_ticket
from . import service_lead
from . import crm_analytics_kpi
from . import crm_conversion_report
from . import crm_sales_performance
from . import crm_customer_retention
from . import crm_lost_reason_analytics
from . import mail_template_campaign
from . import res_partner_campaign
from . import mail_log
from . import mail_campaign
from . import schedule_campaign_wizard
from . import res_partner_personalization
from . import mail_campaign_personalization
from . import mail_template_personalization
from . import loyalty_rule_wizard
from . import crm_campaign_bridge
from . import unified_lead
from . import unified_complaint
from . import demo_data
