{
    "name": "VINATEX CRM",
    "summary": "Nền tảng CRM hiện tại cho Vinatex",
    "version": "17.0.1.0.0",
    "category": "Sales/CRM",
    "author": "Nhóm E",
    "license": "LGPL-3",
    "depends": ["crm", "mail", "sale_management", "utm", "website"],
    "data": [
        "security/ir.model.access.csv",
        "security/campaign_access.xml",
        "security/crm_lead_data_rules.xml",
        "security/analytics_security_rules.xml",
        "data/crm_pipeline_stage_data.xml",
        "data/approval_sequence.xml",
        "data/complaint_sequence.xml",
        "data/sequence.xml",
        "data/mail_template.xml",
        "data/campaign_email_template.xml",
        "data/campaign_email_template_personalization.xml",
        "data/ir_cron_data.xml",
        "data/cron_job.xml",
        "data/cron.xml",
        "data/campaign_cron_send.xml",
        "data/campaign_cron_personalization.xml",
        "data/campaign_cleanup_templates.xml",
        "data/campaign_recompute_personalization.xml",
        "data/vinatex_demo_data.xml",
        "views/lead_views.xml",
        "views/lead_data_approval_views.xml",
        "wizards/lead_transfer_owner_views.xml",
        "views/mail_campaign_views.xml",
        "views/mail_template_campaign_views.xml",
        "views/schedule_campaign_wizard_views.xml",
        "views/res_partner_personalization_views.xml",
        "views/loyalty_rule_wizard_views.xml",
        "views/mail_campaign_personalization_views.xml",
        "views/cskh_profile_views.xml",
        "views/cskh_lead_views.xml",
        "views/cskh_workflow_rule_views.xml",
        "views/complaint_ticket_views.xml",
        "views/service_lead_views.xml",
        "views/service_dashboard_views.xml",
        "views/crm_analytics_kpi_views.xml",
        "views/crm_conversion_report_views.xml",
        "views/crm_sales_performance_views.xml",
        "views/crm_customer_retention_views.xml",
        "views/crm_lost_reason_analytics_views.xml",
        "views/unified_lead_views.xml",
        "views/unified_complaint_views.xml",
        "views/menu_views.xml",
        "views/campaign_menu.xml",
        "views/personalization_menu.xml",
        "views/website_crm_vinatex_templates.xml",
        "views/website_menu.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "crm_tong_hop/static/src/css/website_crm_vinatex.css",
            "crm_tong_hop/static/src/js/website_crm_vinatex.js",
        ],
        "web.assets_backend": [
            "crm_tong_hop/static/src/css/backend_global.css",
            "crm_tong_hop/static/src/css/dashboard.css",
            "crm_tong_hop/static/src/css/personalization_list.css",
            "crm_tong_hop/static/src/js/dashboard.js",
            "crm_tong_hop/static/src/js/vietnamese_ui_labels.js",
            "crm_tong_hop/static/src/js/cskh_form_helpers.js",
            "crm_tong_hop/static/src/xml/dashboard.xml",
        ],
    },
    "application": True,
    "installable": True,
}
